[package]
name = "day4"
version = "0.1.0"
authors = ["Piszmog <piszmogcode@gmail.com>"]
edition = "2018"

[dependencies]
file_utils = { path = "../../utils/rust/file_utils" }
regex = "1.4.2"
lazy_static = "1.4.0"